name: jael3_fork
version: 8.4.0
description:  A simple server-side HTML templating engine for Dart. Comparable to Blade or Liquid.
homepage: https://github.com/insinfo/jael3
repository: https://github.com/insinfo/jael3
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  args: ^2.4.0
  charcode: ^1.3.0
  belatuk_code_buffer: ^5.1.0
  belatuk_symbol_table: ^5.1.0
  source_span: ^1.10.0
  string_scanner: ^1.2.0
  collection: ^1.17.0
  matcher: ^0.12.10 
  # for jael3_preprocessor
  file: ^7.0.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  path: any
  
executables:
  jaelfmt: jaelfmt